### ISSUE TITLE
Create a script that when run shows the current time for London/New York/Mumbai

### ISSUE THREAD

**Issue by GiovanniBruno22** [GiovanniBruno22/PythonBeginners#1]
Hey! it would be nice if someone could code a script that shows the current time for London/New York/Mumbai when it is ran from terminal.

**Comment by ihavemadefire** [comment]
Hi Giovanni,
Just submitted PR#2 at https://github.com/GiovanniBruno22/PythonBeginners/pull/2
Let me know if it LGTY.

**Comment by GiovanniBruno22** [comment]
Thanks a lot for submitting this repo's first ever PR! I really appreciate your help 😄 I left a few comments on the PR, as soon as those are addressed I will merge the changes in!

**Comment by ihavemadefire** [comment]
I don't see the comments on the PR. Let me know what changes you need to
see and I'll get them pushed. 😊

**Comment by GiovanniBruno22** [comment]
Apologies for that, I forgot to click on publish review 🤣, you should be able to see the comments on your PR now.

**Comment by GiovanniBruno22** [comment]
This has been resolved, thanks a lot @ihavemadefire  for your contribution, I will mark this issue as complete.
