### ISSUE TITLE
NATO Alphabet Translator

### ISSUE THREAD

**Issue by GiovanniBruno22** [GiovanniBruno22/PythonBeginners#10]
Write a program that, after inputting a word, returns the NATO alphabet spelling of the word used as input,  for example:

input : tree

output: 

Tango
Romeo
Echo
Echo

**Comment by harshitkandpal** [comment]
i am interested

**Comment by GiovanniBruno22** [comment]
Sure thing! I will assign this to you 🙂

**Comment by harshitkandpal** [comment]
Thank you very much

**Comment by harshitkandpal** [comment]
Done please check.

**Comment by GiovanniBruno22** [comment]
Hey @harshitkandpal , I can't seem to be able to find the PR for this 🙁

**Comment by GiovanniBruno22** [comment]
Solved! thanks @harshitkandpal !
