### ISSUE TITLE
Create a Tic Tac Toe game, can either be made as a terminal application or with pygame, pyqtgui or tkinter

### ISSUE THREAD

**Issue by GiovanniBruno22** [GiovanniBruno22/PythonBeginners#3]
Hey! It would be great if our games folder would get its' very first entry! Does anyone feel like adding a Tic Tac Toe game? It can either be made with or without UI, as a terminal application, as a pygame, with pyqt or tkinter. Have fun!

**Comment by lcoburn** [comment]
Hi, I am new to open source projects. I would like to work on this issue if that is ok..

**Comment by GiovanniBruno22** [comment]
Sure thing, I will assign this issue to you 😄
