### ISSUE TITLE
Python script/ GUI to calculate dinner total with tip and change.

### ISSUE THREAD

**Issue by GiovanniBruno22** [GiovanniBruno22/PythonBeginners#5]
It would be great if someone could make a script or a GUI application that provides the user with a randomized total amount for their  dinner in dollars,  then asks the user how much they'd like to tip in percentage and then proceed to show the total due.

Once the total amount has been paid, it should also print how much change the cashier should be giving back.

Have fun!

**Comment by Jay-Jay23** [comment]
Hi Giovanni,
Just submitted a script addressing the above
Let me know how i did.

**Comment by GiovanniBruno22** [comment]
Thank you so much for your contribution @Jay-Jay23 ! I have left a few comments on the PR, as soon as those will be addressed I will merge the PR in. 🙂

**Comment by GiovanniBruno22** [comment]
Solved, thanks a lot @Jay-Jay23
