### ISSUE TITLE
Random password generator

### ISSUE THREAD

**Issue by GiovanniBruno22** [GiovanniBruno22/PythonBeginners#8]
Hey, it would be nice if we could have a random password generator that could take as input the password length and then return a password made of alphanumeric and special characters. This could either be done with or without UI.

**Comment by harshitkandpal** [comment]
hi i am interested and able to make it

**Comment by GiovanniBruno22** [comment]
Sure thing @harshitkandpal , I will assign this issue to you 🙂

**Comment by harshitkandpal** [comment]
thankyou very much

**Comment by harshitkandpal** [comment]
i think i have done some mistake while making pull request ?

**Comment by y9rabbito** [comment]
I have submitted a pull request regarding the issue #8 @GiovanniBruno22  you review it and take necessary action.

**Comment by GiovanniBruno22** [comment]
Thanks a lot for your contribution @y9rabbito 😃

**Comment by GiovanniBruno22** [comment]
Thanks a lot @harshitkandpal for adding the random password generator!
